# Generated by Django 5.1.7 on 2025-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('reviews', models.DecimalField(decimal_places=2, max_digits=50)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
